### ISSUE TITLE
Specify requirements.txt

### ISSUE THREAD

**Issue by lccnl** [davisyoshida/easy-lora-and-gptq#2]
Hello,
I am trying to reproduce the notebook (which btw is super cool!) but I am encountering some issues due to the CuSolver.
Basically, in the quantization method, I have an `internal Cusolver Error` whenever jax.scipy.linalg or jax.numpy.linalg is called (while it works if I remove jit and replace these calls by standard numpy and scipy functions).
There are a couple issues on that in the jax repo but the solutions proposed (changing memory preallocation mainly) do not seem to work.

Could you specify your setup? Like jax/jaxlib versions you tested with nvidia drivers.

Thank you very much!

**Comment by davisyoshida** [comment]
Hmm this notebook is a little out of date too since I've significantly updated lorax. Also I put this up before QLora was around, which is probably better for a lot of use cases. Out of curiosity, what sort of use case are you looking at?

**Comment by davisyoshida** [comment]
I've also added a requirements.txt. This notebook is set up to work on Google colab though, so if you just click the run in colab button on the README, you should be able to interactively mess with it.

**Comment by lccnl** [comment]
Thank you very much for your quick answer! Yes, indeed I saw that lorax had changed quite since you made this notebook, but I wanted to try it first, to see how good the model was after quantisation. 

In my use case, I need to finetune the model with dpsgd and there are not many benchmarks on how it performs with quantization and lora...

My understanding is that if I want to implement Qlora I can use lorax+ the implementation of 4bit quantization that you have done for the note on Qlora (which by the way was really helpful too!). This though is not super efficient because matrix multiplication for the quantized weight will cause rematerialisation all the time. 

But I guess I could use part of the code you wrote for gptq for efficient matrix multiplication right to handle the dot_general of the QuantizedMatrix, following the qax api right?

**Comment by davisyoshida** [comment]
@lccnl You can try messing around with the triton kernel I made for GPTQ yeah. I got some speedup at inference time using it but it's not amazing. Also I've had endless CUDA issues using Triton so I definitely won't know how to help if you run into any issues like that.
